// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BlhDbContext))]
    [Migration("20260523160701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "perfil_usuario", new[] { "admin", "blh_admin", "enfermeira", "campo", "laboratorio", "estoque", "distribuicao", "hospital", "medico", "nutricionista" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.AdministracaoFrasco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrascoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid>("PrescricaoLeiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VolumeAdministradoMl")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("AdministracoesFrasco");
                });

            modelBuilder.Entity("Domain.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("text");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("text");

                    b.Property<string>("Dispositivo")
                        .HasColumnType("text");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Domain.CaixaTermica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacidadeLitros")
                        .HasColumnType("numeric");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CaixasTermicas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CapacidadeLitros = 12m,
                            Codigo = "CX-001",
                            Descricao = "Caixa termica principal",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.Coleta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaixaTermicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoadoraId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RotaColetaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemperaturaAmbiente")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TemperaturaCaixaFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TemperaturaCaixaInicial")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Coletas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CaixaTermicaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            DataHoraFim = new DateTime(2026, 5, 23, 10, 35, 0, 0, DateTimeKind.Utc),
                            DataHoraInicio = new DateTime(2026, 5, 23, 10, 20, 0, 0, DateTimeKind.Utc),
                            DoadoraId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Latitude = -22.2088m,
                            Longitude = -49.9345m,
                            ResponsavelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RotaColetaId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Status = 2,
                            TemperaturaAmbiente = 24m,
                            TemperaturaCaixaFinal = 4.2m,
                            TemperaturaCaixaInicial = 3.8m
                        });
                });

            modelBuilder.Entity("Domain.ControleQualidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AcidezDornic")
                        .HasColumnType("numeric");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<bool>("CorConforme")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Crematocrito")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrascoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<bool>("OdorConforme")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultadoMicrobiologico")
                        .HasColumnType("text");

                    b.Property<bool>("SujidadeAusente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ControlesQualidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AcidezDornic = 4m,
                            Aprovado = true,
                            CorConforme = true,
                            Crematocrito = 6m,
                            DataHora = new DateTime(2026, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            FrascoId = new Guid("88888888-8888-8888-8888-888888888888"),
                            LoteId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            OdorConforme = true,
                            ResponsavelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ResultadoMicrobiologico = "Ausente",
                            SujidadeAusente = true
                        });
                });

            modelBuilder.Entity("Domain.Distribuicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaixaTermicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescricaoLeiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsavelEntregaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsavelSeparacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemperaturaSaida")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Distribuicoes");
                });

            modelBuilder.Entity("Domain.DistribuicaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DistribuicaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrascoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VolumeMl")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DistribuicaoItens");
                });

            modelBuilder.Entity("Domain.Doadora", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CNS")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataParto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("TipoParto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doadoras");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CNS = "700000000000001",
                            CPF = "12345678901",
                            CriadoEm = new DateTime(2026, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            DataNascimento = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataParto = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@example.com",
                            Endereco = "Rua das Flores, 50",
                            Latitude = -22.2088m,
                            Longitude = -49.9345m,
                            Nome = "Maria Doadora",
                            Status = 3,
                            Telefone = "(14) 99999-0001",
                            TipoParto = "Normal"
                        });
                });

            modelBuilder.Entity("Domain.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrascoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Freezer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Posicao")
                        .HasColumnType("text");

                    b.Property<string>("Prateleira")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemperaturaAtual")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoEstoque")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Estoques");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            DataEntrada = new DateTime(2026, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            DataValidade = new DateTime(2026, 11, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            FrascoId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Freezer = "FZ-01",
                            Posicao = "01",
                            Prateleira = "A",
                            Status = 1,
                            TemperaturaAtual = -18m,
                            TipoEstoque = 1
                        });
                });

            modelBuilder.Entity("Domain.ExameDoadora", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExame")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoadoraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoExame")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Valido")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ExamesDoadora");
                });

            modelBuilder.Entity("Domain.Frasco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaixaTermicaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ColetaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataOrdenhaFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataOrdenhaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoadoraId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TemperaturaColeta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TemperaturaRecepcao")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoLeite")
                        .HasColumnType("integer");

                    b.Property<decimal>("VolumeMl")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.ToTable("Frascos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CaixaTermicaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CodigoUnico = "BLH-2026-0001",
                            ColetaId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2026, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoadoraId = new Guid("44444444-4444-4444-4444-444444444444"),
                            LoteId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            QrCode = "BLH-2026-0001",
                            Status = 6,
                            TemperaturaColeta = 4.1m,
                            TemperaturaRecepcao = 4.4m,
                            TipoLeite = 2,
                            VolumeMl = 120m
                        });
                });

            modelBuilder.Entity("Domain.Instituicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("CNES")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Instituicoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativa = true,
                            CNES = "0000001",
                            CNPJ = "00000000000100",
                            Endereco = "Av. Central, 100",
                            Latitude = -22.2135m,
                            Longitude = -49.9450m,
                            Municipio = "Marilia",
                            Nome = "Banco de Leite Humano Exemplo",
                            Tipo = 0,
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Ativa = true,
                            CNES = "0000002",
                            CNPJ = "00000000000200",
                            Endereco = "Rua Saude, 200",
                            Latitude = -22.2170m,
                            Longitude = -49.9505m,
                            Municipio = "Marilia",
                            Nome = "Hospital Materno Infantil",
                            Tipo = 1,
                            UF = "SP"
                        });
                });

            modelBuilder.Entity("Domain.LoteProcessamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LotesProcessamento");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CodigoLote = "LOTE-2026-001",
                            DataFim = new DateTime(2026, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            DataInicio = new DateTime(2026, 5, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observacoes = "Lote seed aprovado",
                            ResponsavelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 3
                        });
                });

            modelBuilder.Entity("Domain.PrescricaoLeite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Horarios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JustificativaClinica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfissionalSolicitanteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceptorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TipoLeiteSolicitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VolumeDiarioMl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VolumePorHorarioMl")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PrescricoesLeite");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CriadoEm = new DateTime(2026, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Horarios = "06:00,09:00,12:00,15:00,18:00,21:00",
                            JustificativaClinica = "Prematuridade e baixo peso",
                            ProfissionalSolicitanteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReceptorId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Status = 0,
                            TipoLeiteSolicitado = "Pasteurizado",
                            VolumeDiarioMl = 120m,
                            VolumePorHorarioMl = 20m
                        });
                });

            modelBuilder.Entity("Domain.ProcessamentoFrasco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FrascoDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrascoOrigemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoProcessamento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProcessamentosFrasco");
                });

            modelBuilder.Entity("Domain.RecebimentoHospital", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Conforme")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistribuicaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelRecebimentoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TemperaturaChegada")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("RecebimentosHospital");
                });

            modelBuilder.Entity("Domain.RecepcaoBLH", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Conforme")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmbalagemIntegra")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FrascoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoNaoConformidade")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RotuloConforme")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TemperaturaChegada")
                        .HasColumnType("numeric");

                    b.Property<bool>("VolumeConforme")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("RecepcoesBLH");
                });

            modelBuilder.Entity("Domain.Receptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CNS")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdadeGestacional")
                        .HasColumnType("integer");

                    b.Property<string>("Leito")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PesoNascimento")
                        .HasColumnType("numeric");

                    b.Property<string>("Prontuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Receptores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CNS = "700000000000002",
                            DataNascimento = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnostico = "Prematuridade",
                            HospitalId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IdadeGestacional = 31,
                            Leito = "03",
                            Nome = "Bebe Receptor",
                            PesoNascimento = 1.25m,
                            Prontuario = "PR-001",
                            Setor = "UTI Neonatal",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Domain.RegistroRastreamentoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaixaTermicaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ColetaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DistribuicaoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("OrigemRegistro")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RotaColetaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoRegistro")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaixaTermicaId", "DataHoraRegistro");

                    b.ToTable("RegistrosRastreamentoCaixa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-0001-0000-0000-000000000001"),
                            CaixaTermicaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ColetaId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2026, 5, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            DataHoraRegistro = new DateTime(2026, 5, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = -22.2135m,
                            Longitude = -49.9450m,
                            Observacao = "Saida do BLH",
                            OrigemRegistro = 1,
                            RotaColetaId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Temperatura = 3.7m,
                            TipoRegistro = 0,
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0002-0000-0000-000000000002"),
                            CaixaTermicaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ColetaId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2026, 5, 23, 10, 8, 0, 0, DateTimeKind.Utc),
                            DataHoraRegistro = new DateTime(2026, 5, 23, 10, 8, 0, 0, DateTimeKind.Utc),
                            Latitude = -22.2116m,
                            Longitude = -49.9418m,
                            Observacao = "Temperatura durante deslocamento",
                            OrigemRegistro = 1,
                            RotaColetaId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Temperatura = 3.9m,
                            TipoRegistro = 3,
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0003-0000-0000-000000000003"),
                            CaixaTermicaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ColetaId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2026, 5, 23, 10, 20, 0, 0, DateTimeKind.Utc),
                            DataHoraRegistro = new DateTime(2026, 5, 23, 10, 20, 0, 0, DateTimeKind.Utc),
                            Latitude = -22.2088m,
                            Longitude = -49.9345m,
                            Observacao = "Chegada na doadora",
                            OrigemRegistro = 1,
                            RotaColetaId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Temperatura = 4.1m,
                            TipoRegistro = 1,
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0004-0000-0000-000000000004"),
                            CaixaTermicaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ColetaId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2026, 5, 23, 10, 35, 0, 0, DateTimeKind.Utc),
                            DataHoraRegistro = new DateTime(2026, 5, 23, 10, 35, 0, 0, DateTimeKind.Utc),
                            Latitude = -22.2088m,
                            Longitude = -49.9345m,
                            Observacao = "Coleta realizada",
                            OrigemRegistro = 1,
                            RotaColetaId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Temperatura = 4.2m,
                            TipoRegistro = 2,
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0005-0000-0000-000000000005"),
                            CaixaTermicaId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ColetaId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CriadoEm = new DateTime(2026, 5, 23, 10, 55, 0, 0, DateTimeKind.Utc),
                            DataHoraRegistro = new DateTime(2026, 5, 23, 10, 55, 0, 0, DateTimeKind.Utc),
                            Latitude = -22.2135m,
                            Longitude = -49.9450m,
                            Observacao = "Retorno ao BLH",
                            OrigemRegistro = 1,
                            RotaColetaId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Temperatura = 4.4m,
                            TipoRegistro = 4,
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Domain.RotaColeta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaSemana")
                        .HasColumnType("text");

                    b.Property<string>("Motorista")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Veiculo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RotasColeta");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            DataInicio = new DateTime(2026, 5, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            DiaSemana = "Segunda",
                            Motorista = "Joao",
                            Nome = "Rota Norte - Manha",
                            ResponsavelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 1,
                            Veiculo = "Van BLH 01"
                        });
                });

            modelBuilder.Entity("Domain.TriagemDoadora", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoadoraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("text");

                    b.Property<string>("Parecer")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Tabagista")
                        .HasColumnType("boolean");

                    b.Property<bool>("TatuagemOuPiercingUltimos12Meses")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemHIV")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemHepatite")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemSifilis")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsaAlcool")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsaDrogas")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsaMedicamento")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TriagensDoadora");
                });

            modelBuilder.Entity("Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 5, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@blh.local",
                            Nome = "Administrador BLH",
                            Perfil = 0,
                            SenhaHash = "seed-admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
