namespace Domain;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); }

public class Usuario : Entity { public string Nome { get; set; } = ""; public string Email { get; set; } = ""; public string SenhaHash { get; set; } = ""; public PerfilUsuario Perfil { get; set; } public bool Ativo { get; set; } = true; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class Instituicao : Entity { public string Nome { get; set; } = ""; public TipoInstituicao Tipo { get; set; } public string? CNES { get; set; } public string? CNPJ { get; set; } public string Endereco { get; set; } = ""; public string Municipio { get; set; } = ""; public string UF { get; set; } = ""; public decimal? Latitude { get; set; } public decimal? Longitude { get; set; } public bool Ativa { get; set; } = true; }
public class Doadora : Entity { public string Nome { get; set; } = ""; public string CPF { get; set; } = ""; public string? CNS { get; set; } public DateTime DataNascimento { get; set; } public string? Telefone { get; set; } public string? Email { get; set; } public string Endereco { get; set; } = ""; public decimal? Latitude { get; set; } public decimal? Longitude { get; set; } public DateTime? DataParto { get; set; } public string? TipoParto { get; set; } public StatusDoadora Status { get; set; } = StatusDoadora.PreCadastro; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class TriagemDoadora : Entity { public Guid DoadoraId { get; set; } public bool TemHIV { get; set; } public bool TemHepatite { get; set; } public bool TemSifilis { get; set; } public bool UsaMedicamento { get; set; } public string? Medicamentos { get; set; } public bool Tabagista { get; set; } public bool UsaAlcool { get; set; } public bool UsaDrogas { get; set; } public bool TatuagemOuPiercingUltimos12Meses { get; set; } public bool Aprovada { get; set; } public string? Parecer { get; set; } public Guid ResponsavelId { get; set; } public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class ExameDoadora : Entity { public Guid DoadoraId { get; set; } public string TipoExame { get; set; } = ""; public DateTime DataExame { get; set; } public string Resultado { get; set; } = ""; public string? ArquivoUrl { get; set; } public bool Valido { get; set; } public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class RotaColeta : Entity { public string Nome { get; set; } = ""; public string? DiaSemana { get; set; } public string? Veiculo { get; set; } public string? Motorista { get; set; } public Guid ResponsavelId { get; set; } public StatusRota Status { get; set; } = StatusRota.Planejada; public DateTime? DataInicio { get; set; } public DateTime? DataFim { get; set; } }
public class CaixaTermica : Entity { public string Codigo { get; set; } = ""; public string? Descricao { get; set; } public decimal CapacidadeLitros { get; set; } public StatusCaixaTermica Status { get; set; } = StatusCaixaTermica.Disponivel; }
public class Coleta : Entity { public Guid DoadoraId { get; set; } public Guid RotaColetaId { get; set; } public Guid CaixaTermicaId { get; set; } public Guid ResponsavelId { get; set; } public DateTime? DataHoraInicio { get; set; } public DateTime? DataHoraFim { get; set; } public decimal? Latitude { get; set; } public decimal? Longitude { get; set; } public decimal? TemperaturaCaixaInicial { get; set; } public decimal? TemperaturaCaixaFinal { get; set; } public decimal? TemperaturaAmbiente { get; set; } public string? Observacoes { get; set; } public StatusColeta Status { get; set; } = StatusColeta.Agendada; }
public class Frasco : Entity { public string CodigoUnico { get; set; } = ""; public string? QrCode { get; set; } public Guid DoadoraId { get; set; } public Guid ColetaId { get; set; } public Guid CaixaTermicaId { get; set; } public Guid? LoteId { get; set; } public TipoLeite TipoLeite { get; set; } = TipoLeite.NaoClassificado; public decimal VolumeMl { get; set; } public StatusFrasco Status { get; set; } = StatusFrasco.Coletado; public DateTime? DataOrdenhaInicio { get; set; } public DateTime? DataOrdenhaFim { get; set; } public decimal? TemperaturaColeta { get; set; } public decimal? TemperaturaRecepcao { get; set; } public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class RegistroRastreamentoCaixa : Entity { public Guid CaixaTermicaId { get; set; } public Guid? RotaColetaId { get; set; } public Guid? ColetaId { get; set; } public Guid? DistribuicaoId { get; set; } public Guid UsuarioId { get; set; } public TipoRegistroCaixa TipoRegistro { get; set; } public decimal Latitude { get; set; } public decimal Longitude { get; set; } public decimal Temperatura { get; set; } public DateTime DataHoraRegistro { get; set; } public string? Observacao { get; set; } public OrigemRegistro OrigemRegistro { get; set; } = OrigemRegistro.Web; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class RecepcaoBLH : Entity { public Guid FrascoId { get; set; } public Guid ResponsavelId { get; set; } public DateTime DataHora { get; set; } = DateTime.UtcNow; public decimal TemperaturaChegada { get; set; } public bool EmbalagemIntegra { get; set; } public bool RotuloConforme { get; set; } public bool VolumeConforme { get; set; } public bool Conforme { get; set; } public string? MotivoNaoConformidade { get; set; } }
public class LoteProcessamento : Entity { public string CodigoLote { get; set; } = ""; public DateTime DataInicio { get; set; } = DateTime.UtcNow; public DateTime? DataFim { get; set; } public Guid ResponsavelId { get; set; } public StatusLote Status { get; set; } = StatusLote.Aberto; public string? Observacoes { get; set; } }
public class ProcessamentoFrasco : Entity { public Guid LoteId { get; set; } public Guid FrascoOrigemId { get; set; } public Guid? FrascoDestinoId { get; set; } public TipoProcessamento TipoProcessamento { get; set; } public DateTime DataHora { get; set; } = DateTime.UtcNow; public Guid ResponsavelId { get; set; } public string? Observacoes { get; set; } }
public class ControleQualidade : Entity { public Guid FrascoId { get; set; } public Guid LoteId { get; set; } public decimal? AcidezDornic { get; set; } public decimal? Crematocrito { get; set; } public bool CorConforme { get; set; } public bool OdorConforme { get; set; } public bool SujidadeAusente { get; set; } public string? ResultadoMicrobiologico { get; set; } public bool Aprovado { get; set; } public Guid ResponsavelId { get; set; } public DateTime DataHora { get; set; } = DateTime.UtcNow; public string? Observacoes { get; set; } }
public class Estoque : Entity { public Guid FrascoId { get; set; } public TipoEstoque TipoEstoque { get; set; } public string Freezer { get; set; } = ""; public string? Prateleira { get; set; } public string? Posicao { get; set; } public decimal? TemperaturaAtual { get; set; } public DateTime DataEntrada { get; set; } = DateTime.UtcNow; public DateTime DataValidade { get; set; } public StatusEstoque Status { get; set; } = StatusEstoque.Disponivel; }
public class Receptor : Entity { public string Nome { get; set; } = ""; public string? CNS { get; set; } public string Prontuario { get; set; } = ""; public DateTime DataNascimento { get; set; } public int? IdadeGestacional { get; set; } public decimal? PesoNascimento { get; set; } public string? Diagnostico { get; set; } public Guid HospitalId { get; set; } public string? Setor { get; set; } public string? Leito { get; set; } public StatusReceptor Status { get; set; } = StatusReceptor.Internado; }
public class PrescricaoLeite : Entity { public Guid ReceptorId { get; set; } public Guid ProfissionalSolicitanteId { get; set; } public string TipoLeiteSolicitado { get; set; } = ""; public decimal VolumeDiarioMl { get; set; } public decimal VolumePorHorarioMl { get; set; } public string Horarios { get; set; } = ""; public string JustificativaClinica { get; set; } = ""; public StatusPrescricao Status { get; set; } = StatusPrescricao.Aberta; public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
public class Distribuicao : Entity { public Guid PrescricaoLeiteId { get; set; } public Guid HospitalId { get; set; } public Guid CaixaTermicaId { get; set; } public Guid ResponsavelSeparacaoId { get; set; } public Guid? ResponsavelEntregaId { get; set; } public DateTime? DataHoraSaida { get; set; } public decimal? TemperaturaSaida { get; set; } public StatusDistribuicao Status { get; set; } = StatusDistribuicao.EmSeparacao; }
public class DistribuicaoItem : Entity { public Guid DistribuicaoId { get; set; } public Guid FrascoId { get; set; } public decimal VolumeMl { get; set; } }
public class RecebimentoHospital : Entity { public Guid DistribuicaoId { get; set; } public Guid HospitalId { get; set; } public Guid ResponsavelRecebimentoId { get; set; } public DateTime DataHora { get; set; } = DateTime.UtcNow; public decimal TemperaturaChegada { get; set; } public bool Conforme { get; set; } public string? Observacoes { get; set; } }
public class AdministracaoFrasco : Entity { public Guid FrascoId { get; set; } public Guid ReceptorId { get; set; } public Guid PrescricaoLeiteId { get; set; } public Guid ProfissionalId { get; set; } public DateTime DataHora { get; set; } = DateTime.UtcNow; public decimal VolumeAdministradoMl { get; set; } public string? Observacoes { get; set; } }
public class Auditoria : Entity { public Guid UsuarioId { get; set; } public string Acao { get; set; } = ""; public string Entidade { get; set; } = ""; public Guid EntidadeId { get; set; } public string? DadosAntes { get; set; } public string? DadosDepois { get; set; } public string? Ip { get; set; } public string? Dispositivo { get; set; } public decimal? Latitude { get; set; } public decimal? Longitude { get; set; } public DateTime CriadoEm { get; set; } = DateTime.UtcNow; }
